/**
 * Generate PDF monthly statement
 * Uses jsPDF + jspdf-autotable (already in dependencies)
 */
export async function generateMonthlyPDF(
  month: string,
  expenses: any[],
  income: number,
  expenseTotal: number,
  balance: number,
  openingBalance: number
) {
  const jsPDFModule = await import('jspdf');
  const { jsPDF } = jsPDFModule.default ?? jsPDFModule;
  await import('jspdf-autotable');

  const doc = new jsPDF();
  const pageWidth  = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 20;

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('FinWise — Monthly Statement', pageWidth / 2, y, { align: 'center' });

  y += 10;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Period: ${month}`, 20, y);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 20, y, { align: 'right' });

  // ── Summary ───────────────────────────────────────────────────────────────
  y += 14;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 20, y);

  (doc as any).autoTable({
    head: [['Item', 'Amount']],
    body: [
      ['Opening Balance', openingBalance.toFixed(2)],
      ['Total Income',    `+${income.toFixed(2)}`],
      ['Total Expenses',  `-${expenseTotal.toFixed(2)}`],
      ['Closing Balance', balance.toFixed(2)],
    ],
    startY: y + 4,
    theme: 'grid',
    headStyles: { fillColor: [99, 102, 241] }, // indigo
    columnStyles: { 1: { halign: 'right' } },
    margin: { left: 20, right: 20 },
  });

  y = (doc as any).lastAutoTable.finalY + 12;

  // ── Transactions ──────────────────────────────────────────────────────────
  if (expenses.length > 0) {
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Transactions', 20, y);

    const rows = expenses
      .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
      .map((e) => [
        new Date(e.date).toLocaleDateString(),
        e.category || '—',
        e.type === 'income' ? 'IN' : 'OUT',
        `${e.amount.toFixed(2)}`,
        e.description || '',
      ]);

    (doc as any).autoTable({
      head: [['Date', 'Category', 'Type', 'Amount', 'Notes']],
      body: rows,
      startY: y + 4,
      theme: 'striped',
      headStyles: { fillColor: [99, 102, 241] },
      columnStyles: { 3: { halign: 'right' } },
      margin: { left: 20, right: 20 },
    });
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by FinWise · finwise.app', pageWidth / 2, pageHeight - 8, { align: 'center' });

  return doc;
}
